services:
  # Backend API Service
  - type: web
    name: edonuops-backend
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python init_database.py
      gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///edonuops.db
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: edonuops-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://edonuops-backend.onrender.com
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
