#!/usr/bin/env python3
"""
🔒 EdonuOps ERP - Secure Environment Setup Script
================================================

This script helps you set up secure environment variables for the ERP system.
It ensures no sensitive credentials are hardcoded in the source code.

Usage:
    python setup_secure_env.py

Author: EdonuOps Team
Date: 2024
"""

import os
import secrets
import getpass
from pathlib import Path

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_urlsafe(32)

def generate_jwt_secret():
    """Generate a secure JWT secret"""
    return secrets.token_urlsafe(32)

def create_env_file():
    """Create a secure .env file with user input"""
    
    print("🔒 EdonuOps ERP - Secure Environment Setup")
    print("=" * 50)
    print("This script will help you create a secure .env file.")
    print("All sensitive data will be stored in environment variables.")
    print()
    
    # Get user input for sensitive data
    print("📧 AWS SES Configuration:")
    aws_access_key = getpass.getpass("Enter your AWS Access Key ID: ")
    aws_secret_key = getpass.getpass("Enter your AWS Secret Access Key: ")
    ses_smtp_user = getpass.getpass("Enter your SES SMTP Username: ")
    ses_smtp_pass = getpass.getpass("Enter your SES SMTP Password: ")
    
    print("\n🗄️ Database Configuration:")
    db_password = getpass.getpass("Enter your PostgreSQL password: ")
    
    print("\n🔐 Security Configuration:")
    print("Generating secure secret keys...")
    secret_key = generate_secret_key()
    jwt_secret = generate_jwt_secret()
    
    # Create .env file content
    env_content = f"""# EdonuOps ERP - Environment Variables
# Generated by setup_secure_env.py
# NEVER commit this file to version control!

# Application Environment
FLASK_ENV=development
DEBUG=False

# Security Configuration - Generated secure secrets
SECRET_KEY={secret_key}
JWT_SECRET_KEY={jwt_secret}
DEV_JWT_SECRET={generate_secret_key()}
STAGING_JWT_SECRET={generate_secret_key()}
PROD_JWT_SECRET={generate_secret_key()}

# Database Configuration
DATABASE_URL=postgresql://postgres:{db_password}@edonuerp-db.closysmuia9z.eu-north-1.rds.amazonaws.com:5432/postgres?sslmode=require
DB_HOST=edonuerp-db.closysmuia9z.eu-north-1.rds.amazonaws.com
DB_PORT=5432
DB_NAME=postgres
DB_USER=postgres
DB_PASSWORD={db_password}
DB_REGION=eu-north-1
DB_SSL_MODE=require

# AWS SES SMTP Configuration
AWS_REGION=eu-north-1
AWS_ACCESS_KEY_ID={aws_access_key}
AWS_SECRET_ACCESS_KEY={aws_secret_key}
SES_SMTP_USER={ses_smtp_user}
SES_SMTP_PASS={ses_smtp_pass}
SES_FROM_EMAIL=info@edonuerp.com
SES_FROM_NAME=EdonuOps ERP

# Frontend Configuration
FRONTEND_URL=http://localhost:3000
DEV_CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001

# Default Configuration
DEFAULT_TENANT_ID=default
DEFAULT_USER_ID=1
DEFAULT_ROLE=user
DEFAULT_PERMISSIONS=read,write

# Flask Configuration
FLASK_HOST=0.0.0.0
FLASK_PORT=5000
"""
    
    # Write .env file
    env_path = Path(".env")
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"\n✅ Secure .env file created at: {env_path.absolute()}")
    print("\n🔒 Security Notes:")
    print("- The .env file is automatically ignored by git")
    print("- All sensitive credentials are now in environment variables")
    print("- Never share or commit the .env file")
    print("- Rotate credentials regularly in production")
    
    # Verify .gitignore
    gitignore_path = Path(".gitignore")
    if gitignore_path.exists():
        with open(gitignore_path, "r") as f:
            gitignore_content = f.read()
            if ".env" not in gitignore_content:
                print("\n⚠️  WARNING: .env is not in .gitignore!")
                print("Add '.env' to your .gitignore file to prevent accidental commits.")
    else:
        print("\n⚠️  WARNING: No .gitignore file found!")
        print("Create a .gitignore file with '.env' to prevent accidental commits.")

def main():
    """Main function"""
    try:
        create_env_file()
        print("\n🎉 Environment setup complete!")
        print("You can now run your application securely.")
    except KeyboardInterrupt:
        print("\n❌ Setup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")

if __name__ == "__main__":
    main()














































